/**
 * @file page-registry.ts
 * @purpose Registry aller bearbeitbaren Seiten und ihrer Textelemente.
 */

import type { EditablePageDefinition } from "./page-editor-types";

export const EDITABLE_PAGE_REGISTRY: EditablePageDefinition[] = [
  {
    id: "home",
    name: "Startseite",
    path: "/",
    category: "public",
    priority: 1,
    textKeys: [
      { key: "home.hero.eyebrow", label: "Hero — Eyebrow", elementType: "subheading" },
      { key: "home.hero.title", label: "Hero — Hauptüberschrift", elementType: "heading" },
      { key: "home.hero.subtitle", label: "Hero — Untertitel", elementType: "text" },
      { key: "home.hero.cta_primary", label: "Hero — Button primär", elementType: "button" },
      { key: "home.hero.cta_secondary", label: "Hero — Button sekundär", elementType: "button" },
      { key: "home.hero.image", label: "Hero — Hintergrundbild", elementType: "image" },
      { key: "home.hero.image_alt", label: "Hero — Bild Alternativtext", elementType: "text" },
      { key: "home.hero.logo", label: "Hero — Logo", elementType: "image" },
      { key: "home.hero.stat1.label", label: "Hero — Statistik 1 Beschriftung (Wert live aus DB)", elementType: "text" },
      { key: "home.hero.stat2.label", label: "Hero — Statistik 2 Beschriftung (Wert live aus DB)", elementType: "text" },
      { key: "home.hero.stat3.label", label: "Hero — Statistik 3 Beschriftung (Wert live aus DB)", elementType: "text" },
      { key: "home.philosophy.eyebrow", label: "Philosophie — Eyebrow", elementType: "subheading" },
      { key: "home.philosophy.title_line1", label: "Philosophie — Titel Zeile 1", elementType: "heading" },
      { key: "home.philosophy.title_line2", label: "Philosophie — Titel Zeile 2", elementType: "heading" },
      { key: "home.philosophy.intro1", label: "Philosophie — Einleitung 1", elementType: "text" },
      { key: "home.philosophy.intro2", label: "Philosophie — Einleitung 2", elementType: "text" },
      { key: "home.philosophy.quote", label: "Philosophie — Zitat", elementType: "text" },
      { key: "home.philosophy.portrait.name", label: "Philosophie — Porträt Name", elementType: "text" },
      { key: "home.philosophy.portrait.role", label: "Philosophie — Porträt Rolle", elementType: "text" },
      { key: "home.philosophy.portrait.tagline", label: "Philosophie — Porträt Tagline", elementType: "text" },
      { key: "home.philosophy.cta_primary", label: "Philosophie — Button primär", elementType: "button" },
      { key: "home.philosophy.cta_secondary", label: "Philosophie — Button sekundär", elementType: "button" },
      { key: "home.philosophy.value1.title", label: "Philosophie — Wert 1 Titel", elementType: "heading" },
      { key: "home.philosophy.value1.description", label: "Philosophie — Wert 1 Text", elementType: "text" },
      { key: "home.philosophy.value2.title", label: "Philosophie — Wert 2 Titel", elementType: "heading" },
      { key: "home.philosophy.value2.description", label: "Philosophie — Wert 2 Text", elementType: "text" },
      { key: "home.philosophy.value3.title", label: "Philosophie — Wert 3 Titel", elementType: "heading" },
      { key: "home.philosophy.value3.description", label: "Philosophie — Wert 3 Text", elementType: "text" },
      { key: "home.philosophy.value4.title", label: "Philosophie — Wert 4 Titel", elementType: "heading" },
      { key: "home.philosophy.value4.description", label: "Philosophie — Wert 4 Text", elementType: "text" },
      { key: "home.philosophy.value5.title", label: "Philosophie — Wert 5 Titel", elementType: "heading" },
      { key: "home.philosophy.value5.description", label: "Philosophie — Wert 5 Text", elementType: "text" },
      { key: "home.courses.eyebrow", label: "Kursbereiche — Eyebrow", elementType: "subheading" },
      { key: "home.courses.title", label: "Kursbereiche — Überschrift", elementType: "heading" },
      { key: "home.courses.description", label: "Kursbereiche — Beschreibung", elementType: "text" },
      { key: "home.featured.eyebrow", label: "Empfohlene Kurse — Eyebrow", elementType: "subheading" },
      { key: "home.featured.title", label: "Empfohlene Kurse — Überschrift", elementType: "heading" },
      { key: "home.featured.link", label: "Empfohlene Kurse — Link", elementType: "link" },
      { key: "home.latest.eyebrow", label: "Neueste Kurse — Eyebrow", elementType: "subheading" },
      { key: "home.latest.title", label: "Neueste Kurse — Überschrift", elementType: "heading" },
      { key: "home.latest.link", label: "Neueste Kurse — Link", elementType: "link" },
      { key: "home.tools.eyebrow", label: "Werkstatt — Eyebrow", elementType: "subheading" },
      { key: "home.tools.title", label: "Werkstatt — Überschrift", elementType: "heading" },
      { key: "home.tools.description", label: "Werkstatt — Beschreibung", elementType: "text" },
      { key: "home.membership.eyebrow", label: "Mitgliedschaft — Eyebrow", elementType: "subheading" },
      { key: "home.membership.title", label: "Mitgliedschaft — Überschrift", elementType: "heading" },
      { key: "home.membership.description", label: "Mitgliedschaft — Beschreibung", elementType: "text" },
      { key: "home.testimonials.eyebrow", label: "Testimonials — Eyebrow (veraltet)", elementType: "subheading" },
      { key: "home.testimonials.title", label: "Testimonials — Überschrift (veraltet)", elementType: "heading" },
      { key: "home.testimonials.description", label: "Testimonials — Beschreibung (veraltet)", elementType: "text" },
      { key: "homepage.reviews.eyebrow", label: "Community-Bewertungen — Eyebrow", elementType: "subheading" },
      { key: "homepage.reviews.title", label: "Community-Bewertungen — Überschrift", elementType: "heading" },
      { key: "homepage.reviews.subtitle", label: "Community-Bewertungen — Untertitel", elementType: "text" },
      { key: "homepage.reviews.empty.title", label: "Community-Bewertungen — Leer Titel", elementType: "heading" },
      { key: "homepage.reviews.empty.description", label: "Community-Bewertungen — Leer Text", elementType: "text" },
      { key: "homepage.reviews.source.platform", label: "Bewertungsquelle — Plattform", elementType: "text" },
      { key: "homepage.reviews.source.course", label: "Bewertungsquelle — Kurs", elementType: "text" },
      { key: "homepage.reviews.readMore", label: "Bewertung — Weiterlesen", elementType: "button" },
      { key: "homepage.reviews.previous", label: "Karussell — Zurück", elementType: "button" },
      { key: "homepage.reviews.next", label: "Karussell — Weiter", elementType: "button" },
      { key: "home.help.eyebrow", label: "Hilfe — Eyebrow", elementType: "subheading" },
      { key: "home.help.title", label: "Hilfe — Überschrift", elementType: "heading" },
      { key: "home.help.description", label: "Hilfe — Beschreibung", elementType: "text" },
      { key: "home.help.cta_title", label: "Hilfe — CTA Titel", elementType: "heading" },
      { key: "home.help.cta_description", label: "Hilfe — CTA Beschreibung", elementType: "text" },
      { key: "home.help.cta_button", label: "Hilfe — CTA Button", elementType: "button" },
      { key: "home.blog.eyebrow", label: "Magazin — Eyebrow", elementType: "subheading" },
      { key: "home.blog.title", label: "Magazin — Überschrift", elementType: "heading" },
      { key: "home.blog.link", label: "Magazin — Link", elementType: "link" },
      { key: "home.community.eyebrow", label: "Community — Eyebrow", elementType: "subheading" },
      { key: "home.community.title", label: "Community — Überschrift", elementType: "heading" },
      { key: "home.community.description", label: "Community — Beschreibung", elementType: "text" },
      { key: "home.community_cta.title", label: "Community-CTA — Titel", elementType: "heading" },
      { key: "home.community_cta.description", label: "Community-CTA — Beschreibung", elementType: "text" },
      { key: "home.community_cta.primary", label: "Community-CTA — Button primär", elementType: "button" },
      { key: "home.community_cta.secondary", label: "Community-CTA — Button sekundär", elementType: "button" },
    ],
  },
  {
    id: "philosophie",
    name: "Meine Philosophie",
    path: "/philosophie",
    category: "public",
    priority: 1,
    textKeys: [
      { key: "philosophy.header.eyebrow", label: "Philosophie — Header Eyebrow", elementType: "subheading" },
      { key: "philosophy.header.title", label: "Philosophie — Header Titel", elementType: "heading" },
      { key: "philosophy.header.description", label: "Philosophie — Header Beschreibung", elementType: "text" },
      { key: "philosophy.header.image", label: "Philosophie — Header Bild", elementType: "image" },
      { key: "philosophy.header.image_alt", label: "Philosophie — Header Alternativtext", elementType: "text" },
      { key: "philosophy.intro.title", label: "Philosophie — Intro Titel", elementType: "heading" },
      { key: "philosophy.intro.text1", label: "Philosophie — Intro Absatz 1", elementType: "text" },
      { key: "philosophy.intro.text2", label: "Philosophie — Intro Absatz 2", elementType: "text" },
      { key: "philosophy.cards.eyebrow", label: "Philosophie — Karten Eyebrow", elementType: "subheading" },
      { key: "philosophy.cards.title", label: "Philosophie — Karten Titel", elementType: "heading" },
      { key: "philosophy.cards.description", label: "Philosophie — Karten Beschreibung", elementType: "text" },
      { key: "philosophy.quote", label: "Philosophie — Zitat", elementType: "text" },
      { key: "philosophy.cta.primary", label: "Philosophie — CTA primär", elementType: "button" },
      { key: "philosophy.cta.secondary", label: "Philosophie — CTA sekundär", elementType: "button" },
      { key: "philosophy.card1.title", label: "Philosophie — Karte 1 Titel", elementType: "heading" },
      { key: "philosophy.card1.description", label: "Philosophie — Karte 1 Text", elementType: "text" },
      { key: "philosophy.card1.image", label: "Philosophie — Karte 1 Bild", elementType: "image" },
      { key: "philosophy.card1.image_alt", label: "Philosophie — Karte 1 Alternativtext", elementType: "text" },
      { key: "philosophy.card1.caption", label: "Philosophie — Karte 1 Bildunterschrift", elementType: "text" },
      { key: "philosophy.card2.title", label: "Philosophie — Karte 2 Titel", elementType: "heading" },
      { key: "philosophy.card2.description", label: "Philosophie — Karte 2 Text", elementType: "text" },
      { key: "philosophy.card2.image", label: "Philosophie — Karte 2 Bild", elementType: "image" },
      { key: "philosophy.card2.image_alt", label: "Philosophie — Karte 2 Alternativtext", elementType: "text" },
      { key: "philosophy.card2.caption", label: "Philosophie — Karte 2 Bildunterschrift", elementType: "text" },
      { key: "philosophy.card3.title", label: "Philosophie — Karte 3 Titel", elementType: "heading" },
      { key: "philosophy.card3.description", label: "Philosophie — Karte 3 Text", elementType: "text" },
      { key: "philosophy.card3.image", label: "Philosophie — Karte 3 Bild", elementType: "image" },
      { key: "philosophy.card3.image_alt", label: "Philosophie — Karte 3 Alternativtext", elementType: "text" },
      { key: "philosophy.card3.caption", label: "Philosophie — Karte 3 Bildunterschrift", elementType: "text" },
      { key: "philosophy.card4.title", label: "Philosophie — Karte 4 Titel", elementType: "heading" },
      { key: "philosophy.card4.description", label: "Philosophie — Karte 4 Text", elementType: "text" },
      { key: "philosophy.card4.image", label: "Philosophie — Karte 4 Bild", elementType: "image" },
      { key: "philosophy.card4.image_alt", label: "Philosophie — Karte 4 Alternativtext", elementType: "text" },
      { key: "philosophy.card4.caption", label: "Philosophie — Karte 4 Bildunterschrift", elementType: "text" },
      { key: "philosophy.card5.title", label: "Philosophie — Karte 5 Titel", elementType: "heading" },
      { key: "philosophy.card5.description", label: "Philosophie — Karte 5 Text", elementType: "text" },
      { key: "philosophy.card5.image", label: "Philosophie — Karte 5 Bild", elementType: "image" },
      { key: "philosophy.card5.image_alt", label: "Philosophie — Karte 5 Alternativtext", elementType: "text" },
      { key: "philosophy.card5.caption", label: "Philosophie — Karte 5 Bildunterschrift", elementType: "text" },
      { key: "philosophy.card6.title", label: "Philosophie — Karte 6 Titel", elementType: "heading" },
      { key: "philosophy.card6.description", label: "Philosophie — Karte 6 Text", elementType: "text" },
      { key: "philosophy.card6.image", label: "Philosophie — Karte 6 Bild", elementType: "image" },
      { key: "philosophy.card6.image_alt", label: "Philosophie — Karte 6 Alternativtext", elementType: "text" },
      { key: "philosophy.card6.caption", label: "Philosophie — Karte 6 Bildunterschrift", elementType: "text" },
    ],
  },
  {
    id: "akademie",
    name: "Akademie",
    path: "/akademie",
    category: "courses",
    priority: 1,
    textKeys: [
      { key: "akademie.header.eyebrow", label: "Akademie — Header Eyebrow", elementType: "subheading" },
      { key: "akademie.header.title", label: "Akademie — Header Titel", elementType: "heading" },
      { key: "akademie.header.description", label: "Akademie — Header Beschreibung", elementType: "text" },
      { key: "akademie.header.image", label: "Akademie — Header Bild", elementType: "image" },
      { key: "akademie.header.image_alt", label: "Akademie — Header Bild Alternativtext", elementType: "text" },
    ],
  },
  {
    id: "kurse",
    name: "Kursübersicht",
    path: "/akademie/kurse",
    category: "courses",
    priority: 1,
    textKeys: [
      { key: "courses.title", label: "Kursübersicht — Titel", elementType: "heading" },
      { key: "courses.subtitle", label: "Kursübersicht — Untertitel", elementType: "text" },
    ],
  },
  {
    id: "mitgliedschaft",
    name: "Mitgliedschaften",
    path: "/mitgliedschaft",
    category: "member",
    priority: 1,
    textKeys: [
      { key: "member.title", label: "Mitgliedschaft — Titel", elementType: "heading" },
      { key: "member.subtitle", label: "Mitgliedschaft — Untertitel", elementType: "text" },
      { key: "member.cta.join", label: "Mitgliedschaft — CTA", elementType: "button" },
    ],
  },
  {
    id: "werkstatt",
    name: "Werkstatt",
    path: "/werkstatt",
    category: "recipes",
    priority: 2,
    textKeys: [
      { key: "werkstatt.header.eyebrow", label: "Werkstatt — Header Eyebrow", elementType: "subheading" },
      { key: "werkstatt.header.title", label: "Werkstatt — Header Titel", elementType: "heading" },
      { key: "werkstatt.header.description", label: "Werkstatt — Header Beschreibung", elementType: "text" },
      { key: "werkstatt.header.image", label: "Werkstatt — Header Bild", elementType: "image" },
      { key: "werkstatt.header.image_alt", label: "Werkstatt — Header Bild Alternativtext", elementType: "text" },
    ],
  },
  {
    id: "rezeptdatenbank",
    name: "Rezeptdatenbank",
    path: "/werkstatt/rezeptdatenbank",
    category: "recipes",
    priority: 2,
    textKeys: [],
  },
  {
    id: "community",
    name: "Community",
    path: "/community",
    category: "community",
    priority: 2,
    textKeys: [],
  },
  {
    id: "login",
    name: "Login",
    path: "/anmelden",
    category: "auth",
    priority: 1,
    textKeys: [
      { key: "auth.login.title", label: "Login — Titel", elementType: "heading" },
      { key: "auth.login.subtitle", label: "Login — Untertitel", elementType: "text" },
    ],
  },
  {
    id: "register",
    name: "Registrierung",
    path: "/registrieren",
    category: "auth",
    priority: 1,
    textKeys: [
      { key: "auth.register.title", label: "Registrierung — Titel", elementType: "heading" },
      { key: "auth.register.subtitle", label: "Registrierung — Untertitel", elementType: "text" },
    ],
  },
  {
    id: "footer",
    name: "Footer (global)",
    path: "/",
    category: "public",
    priority: 1,
    textKeys: [
      { key: "footer.tagline", label: "Footer — Tagline", elementType: "text" },
      { key: "footer.copyright", label: "Footer — Copyright", elementType: "text" },
      { key: "footer.motto", label: "Footer — Motto", elementType: "text" },
    ],
  },
  {
    id: "kontakt",
    name: "Kontakt",
    path: "/kontakt",
    category: "public",
    priority: 2,
    textKeys: [],
  },
  {
    id: "impressum",
    name: "Impressum",
    path: "/impressum",
    category: "legal",
    priority: 3,
    textKeys: [],
  },
  {
    id: "datenschutz",
    name: "Datenschutz",
    path: "/datenschutz",
    category: "legal",
    priority: 3,
    textKeys: [],
  },
  {
    id: "maintenance",
    name: "Wartungsseite",
    path: "/wartung",
    category: "system",
    priority: 3,
    textKeys: [],
  },
  {
    id: "hilfe",
    name: "Hilfe & Unterstützung",
    path: "/hilfe",
    category: "public",
    priority: 2,
    textKeys: [
      { key: "help.title", label: "Hilfe — Titel", elementType: "heading" },
      { key: "help.subtitle", label: "Hilfe — Untertitel", elementType: "text" },
      { key: "help.knowledge.title", label: "Hilfe — Wissensdatenbank Titel", elementType: "heading" },
      { key: "help.knowledge.description", label: "Hilfe — Wissensdatenbank Beschreibung", elementType: "text" },
      { key: "help.tickets.title", label: "Hilfe — Tickets Titel", elementType: "heading" },
      { key: "help.tickets.description", label: "Hilfe — Tickets Beschreibung", elementType: "text" },
      { key: "help.community.title", label: "Hilfe — Community Titel", elementType: "heading" },
      { key: "help.community.description", label: "Hilfe — Community Beschreibung", elementType: "text" },
      { key: "help.master.title", label: "Hilfe — Meister-Support Titel", elementType: "heading" },
      { key: "help.master.description", label: "Hilfe — Meister-Support Beschreibung", elementType: "text" },
      { key: "help.search.placeholder", label: "Hilfe — Suchfeld", elementType: "text" },
      { key: "help.noResults.title", label: "Hilfe — Keine Ergebnisse Titel", elementType: "heading" },
      { key: "help.noResults.description", label: "Hilfe — Keine Ergebnisse Text", elementType: "text" },
      { key: "help.createTicket", label: "Hilfe — Ticket erstellen", elementType: "button" },
      { key: "help.askCommunity", label: "Hilfe — Zum Forum", elementType: "button" },
      { key: "help.masterSupportLocked", label: "Hilfe — Meister gesperrt", elementType: "text" },
    ],
  },
];

export function getEditablePageById(id: string): EditablePageDefinition | undefined {
  return EDITABLE_PAGE_REGISTRY.find((page) => page.id === id);
}

export function getEditablePageByPath(path: string): EditablePageDefinition | undefined {
  return EDITABLE_PAGE_REGISTRY.find((page) => page.path === path);
}
