/**
 * @file platform-text-defaults.ts
 * @purpose Standardtexte mit Fallback — Single Source of Truth für neue Keys.
 */

import type { PlatformTextDefault } from "./platform-text-types";

function t(
  key: string,
  category: PlatformTextDefault["category"],
  label: string,
  defaultValue: string,
  description?: string,
): PlatformTextDefault {
  return { key, category, label, defaultValue, description };
}

export const PLATFORM_TEXT_DEFAULTS: PlatformTextDefault[] = [
  // Startseite — Hero
  t(
    "home.hero.eyebrow",
    "headings",
    "Startseite — Hero Eyebrow",
    "The Crest of Craftsmanship",
  ),
  t(
    "home.hero.title",
    "headings",
    "Startseite — Hero Titel",
    "Handwerkliche Wurstherstellung – Schritt für Schritt zum Meister.",
  ),
  t(
    "home.hero.subtitle",
    "headings",
    "Startseite — Hero Untertitel",
    "Lerne in strukturierten Kursen, nutze präzise Werkzeuge und werde Teil einer Community, die das Fleischerhandwerk lebt.",
  ),
  t("home.hero.cta_primary", "buttons", "Startseite — Hero CTA primär", "Jetzt Mitglied werden"),
  t("home.hero.cta_secondary", "buttons", "Startseite — Hero CTA sekundär", "Kurse entdecken"),
  t("home.courses.eyebrow", "headings", "Startseite — Kursbereiche Eyebrow", "Akademie"),
  t("home.courses.title", "headings", "Startseite — Kursbereiche Titel", "Kursbereiche"),
  t(
    "home.courses.description",
    "headings",
    "Startseite — Kursbereiche Beschreibung",
    "Vom ersten Brät bis zur Wildwurst — finde den passenden Bereich für dein Handwerk.",
  ),
  t("home.featured.eyebrow", "headings", "Startseite — Empfohlene Kurse Eyebrow", "Akademie"),
  t("home.featured.title", "headings", "Startseite — Empfohlene Kurse Titel", "Empfohlene Kurse"),
  t("home.featured.link", "buttons", "Startseite — Empfohlene Kurse Link", "Alle Kurse →"),
  t("home.hero.image", "headings", "Startseite — Hero Hintergrundbild", "/hero-werkstatt.png"),
  t(
    "home.hero.image_alt",
    "headings",
    "Startseite — Hero Bild Alternativtext",
    "Fleischermeister bei der Arbeit – Fleisch zuschneiden in der Werkstatt",
  ),
  t("home.hero.logo", "headings", "Startseite — Hero Logo", "/hero-logo.png"),
  t("home.hero.stat1.value", "headings", "Startseite — Hero Statistik 1 Wert", "120+"),
  t("home.hero.stat1.label", "headings", "Startseite — Hero Statistik 1 Beschriftung", "Lektionen im Kurskatalog"),
  t("home.hero.stat2.value", "headings", "Startseite — Hero Statistik 2 Wert", "2.500+"),
  t("home.hero.stat2.label", "headings", "Startseite — Hero Statistik 2 Beschriftung", "aktive Mitglieder"),
  t("home.hero.stat3.value", "headings", "Startseite — Hero Statistik 3 Wert", "6"),
  t("home.hero.stat3.label", "headings", "Startseite — Hero Statistik 3 Beschriftung", "Werkzeuge in der Werkstatt"),
  t("home.philosophy.eyebrow", "headings", "Startseite — Philosophie Eyebrow", "Philosophie"),
  t("home.philosophy.title_line1", "headings", "Startseite — Philosophie Titel Zeile 1", "Warum ich tue,"),
  t("home.philosophy.title_line2", "headings", "Startseite — Philosophie Titel Zeile 2", "was ich tue."),
  t("home.philosophy.intro1", "headings", "Startseite — Philosophie Einleitung 1", "Gutes Essen beginnt mit Wissen."),
  t(
    "home.philosophy.intro2",
    "headings",
    "Startseite — Philosophie Einleitung 2",
    "Ich glaube, dass jeder verstehen sollte, was in seinen Lebensmitteln steckt. Deshalb zeige ich dir Schritt für Schritt, wie du eigene Wurst, Schinken, Marinaden und Spezialitäten herstellst – bewusst, nachvollziehbar und mit deinem ganz persönlichen Geschmack.",
  ),
  t(
    "home.philosophy.quote",
    "headings",
    "Startseite — Philosophie Zitat",
    "Wer versteht, was in seinem Essen steckt, entscheidet bewusster, genießt intensiver und wird unabhängiger.",
  ),
  t("home.philosophy.portrait.name", "headings", "Startseite — Philosophie Porträt Name", "Ralf Hermanski"),
  t(
    "home.philosophy.portrait.role",
    "headings",
    "Startseite — Philosophie Porträt Rolle",
    "Fleischermeister seit 1994",
  ),
  t(
    "home.philosophy.portrait.tagline",
    "headings",
    "Startseite — Philosophie Porträt Tagline",
    "Handwerk • Wissen • Praxis",
  ),
  t("home.philosophy.cta_primary", "buttons", "Startseite — Philosophie CTA primär", "Unsere Philosophie"),
  t("home.philosophy.cta_secondary", "buttons", "Startseite — Philosophie CTA sekundär", "Kurse entdecken"),
  t("home.philosophy.value1.title", "headings", "Startseite — Philosophie Wert 1 Titel", "Kontrolle zurückgewinnen"),
  t(
    "home.philosophy.value1.description",
    "headings",
    "Startseite — Philosophie Wert 1 Text",
    "Bestimme selbst, welche Zutaten verwendet werden.",
  ),
  t("home.philosophy.value2.title", "headings", "Startseite — Philosophie Wert 2 Titel", "Eigenen Geschmack entwickeln"),
  t(
    "home.philosophy.value2.description",
    "headings",
    "Startseite — Philosophie Wert 2 Text",
    "Nicht die Industrie entscheidet, wie deine Produkte schmecken.",
  ),
  t("home.philosophy.value3.title", "headings", "Startseite — Philosophie Wert 3 Titel", "Handwerk verstehen"),
  t(
    "home.philosophy.value3.description",
    "headings",
    "Startseite — Philosophie Wert 3 Text",
    "Lerne traditionelle Techniken verständlich und praxisnah.",
  ),
  t("home.philosophy.value4.title", "headings", "Startseite — Philosophie Wert 4 Titel", "Wissen bewahren"),
  t(
    "home.philosophy.value4.description",
    "headings",
    "Startseite — Philosophie Wert 4 Text",
    "Erhalte echtes Fleischerwissen für kommende Generationen.",
  ),
  t("home.philosophy.value5.title", "headings", "Startseite — Philosophie Wert 5 Titel", "Stolz auf das Ergebnis"),
  t(
    "home.philosophy.value5.description",
    "headings",
    "Startseite — Philosophie Wert 5 Text",
    "Es gibt kaum etwas Schöneres, als ein eigenes Produkt mit Familie und Freunden zu teilen.",
  ),

  // Philosophie — eigene Seite
  t("philosophy.header.eyebrow", "headings", "Philosophie — Header Eyebrow", "Philosophie"),
  t("philosophy.header.title", "headings", "Philosophie — Header Titel", "Meine Philosophie"),
  t(
    "philosophy.header.description",
    "headings",
    "Philosophie — Header Beschreibung",
    "Handwerk mit Haltung — sechs Grundsätze, die jede Rezeptur, jeden Kurs und jede Beratung bei Alles Wurst prägen.",
  ),
  t(
    "philosophy.header.image",
    "headings",
    "Philosophie — Header Bild",
    "/images/philosophy/header.png",
  ),
  t(
    "philosophy.header.image_alt",
    "headings",
    "Philosophie — Header Bild Alternativtext",
    "Handwerkliche Zutaten auf dem Werktisch — Kräuter, Gewürze und Salz in traditioneller Küche",
  ),
  t("philosophy.intro.title", "headings", "Philosophie — Intro Titel", "Was uns antreibt"),
  t(
    "philosophy.intro.text1",
    "headings",
    "Philosophie — Intro Absatz 1",
    "Gutes Essen beginnt mit Wissen und Verantwortung.",
  ),
  t(
    "philosophy.intro.text2",
    "headings",
    "Philosophie — Intro Absatz 2",
    "Ich zeige dir Schritt für Schritt, wie du Wurst, Schinken und Spezialitäten bewusst herstellst — mit Respekt vor dem Produkt, klaren Zutaten und deinem persönlichen Geschmack.",
  ),
  t("philosophy.cards.eyebrow", "headings", "Philosophie — Karten Eyebrow", "Unsere Grundsätze"),
  t(
    "philosophy.cards.title",
    "headings",
    "Philosophie — Karten Titel",
    "Sechs Säulen unseres Handwerks",
  ),
  t(
    "philosophy.cards.description",
    "headings",
    "Philosophie — Karten Beschreibung",
    "Jede Karte kann im Adminbereich mit finalem Foto, Alternativtext und optionaler Bildunterschrift befüllt werden.",
  ),
  t(
    "philosophy.quote",
    "headings",
    "Philosophie — Zitat",
    "Wer versteht, was in seinem Essen steckt, entscheidet bewusster, genießt intensiver und wird unabhängiger.",
  ),
  t("philosophy.cta.primary", "buttons", "Philosophie — CTA primär", "Kurse entdecken"),
  t("philosophy.cta.secondary", "buttons", "Philosophie — CTA sekundär", "Mitgliedschaft wählen"),

  t("philosophy.card1.title", "headings", "Philosophie — Karte 1 Titel", "Geduld im Handwerk"),
  t(
    "philosophy.card1.description",
    "headings",
    "Philosophie — Karte 1 Text",
    "Gutes Fleisch, saubere Technik und Ruhe in jedem Arbeitsschritt — Qualität braucht Zeit, nicht Eile.",
  ),
  t(
    "philosophy.card1.image",
    "headings",
    "Philosophie — Karte 1 Bild",
    "/images/philosophy/geduld-im-handwerk.png",
  ),
  t(
    "philosophy.card1.image_alt",
    "headings",
    "Philosophie — Karte 1 Alternativtext",
    "Fleischermeister bei der Wurstreifung — Geduld im Handwerk",
  ),
  t("philosophy.card1.caption", "headings", "Philosophie — Karte 1 Bildunterschrift", ""),

  t("philosophy.card2.title", "headings", "Philosophie — Karte 2 Titel", "Respekt vor dem Tier"),
  t(
    "philosophy.card2.description",
    "headings",
    "Philosophie — Karte 2 Text",
    "Ich verarbeite bewusst, achtsam und ohne Verschwendung — aus Achtung vor dem Leben, das uns Nahrung schenkt.",
  ),
  t(
    "philosophy.card2.image",
    "headings",
    "Philosophie — Karte 2 Bild",
    "/images/philosophy/respekt-vor-dem-tier.png",
  ),
  t(
    "philosophy.card2.image_alt",
    "headings",
    "Philosophie — Karte 2 Alternativtext",
    "Rind, Schwein, Schafe und Hühner auf der Weide — Respekt vor dem Tier",
  ),
  t("philosophy.card2.caption", "headings", "Philosophie — Karte 2 Bildunterschrift", ""),

  t("philosophy.card3.title", "headings", "Philosophie — Karte 3 Titel", "Gute Zutaten"),
  t(
    "philosophy.card3.description",
    "headings",
    "Philosophie — Karte 3 Text",
    "Herkunft, Frische und Transparenz stehen an erster Stelle — denn der Geschmack beginnt bei der Auswahl.",
  ),
  t(
    "philosophy.card3.image",
    "headings",
    "Philosophie — Karte 3 Bild",
    "/images/philosophy/gute-zutaten.png",
  ),
  t(
    "philosophy.card3.image_alt",
    "headings",
    "Philosophie — Karte 3 Alternativtext",
    "Frisches Gemüse, Kräuter und Gewürze auf dem Werktisch — Gute Zutaten",
  ),
  t("philosophy.card3.caption", "headings", "Philosophie — Karte 3 Bildunterschrift", ""),

  t(
    "philosophy.card4.title",
    "headings",
    "Philosophie — Karte 4 Titel",
    "So wenig Zusatzstoffe wie möglich",
  ),
  t(
    "philosophy.card4.description",
    "headings",
    "Philosophie — Karte 4 Text",
    "Ich setze auf Verständnis statt Zusatzstoffkatalog — bewusst, reduziert und nachvollziehbar produziert.",
  ),
  t(
    "philosophy.card4.image",
    "headings",
    "Philosophie — Karte 4 Bild",
    "/images/philosophy/wenig-zusatzstoffe.png",
  ),
  t(
    "philosophy.card4.image_alt",
    "headings",
    "Philosophie — Karte 4 Alternativtext",
    "Natürliche Gewürze statt Industrie-Zusatzstoffe — So wenig Zusatzstoffe wie möglich",
  ),
  t("philosophy.card4.caption", "headings", "Philosophie — Karte 4 Bildunterschrift", ""),

  t(
    "philosophy.card5.title",
    "headings",
    "Philosophie — Karte 5 Titel",
    "Freiheit für den eigenen Geschmack",
  ),
  t(
    "philosophy.card5.description",
    "headings",
    "Philosophie — Karte 5 Text",
    "Keine starren Industrierezepte — du entwickelst Aromen, Würzung und Charakter nach deinem eigenen Gusto.",
  ),
  t(
    "philosophy.card5.image",
    "headings",
    "Philosophie — Karte 5 Bild",
    "/images/philosophy/freiheit-geschmack.png",
  ),
  t(
    "philosophy.card5.image_alt",
    "headings",
    "Philosophie — Karte 5 Alternativtext",
    "Gewürze, Kräuter und Rezeptnotizen — Freiheit für den eigenen Geschmack",
  ),
  t("philosophy.card5.caption", "headings", "Philosophie — Karte 5 Bildunterschrift", ""),

  t(
    "philosophy.card6.title",
    "headings",
    "Philosophie — Karte 6 Titel",
    "Fleischermeister aus Leidenschaft",
  ),
  t(
    "philosophy.card6.description",
    "headings",
    "Philosophie — Karte 6 Text",
    "Über drei Jahrzehnte Handwerk, Wissen teilen und andere auf ihrem Weg begleiten — das ist meine Motivation.",
  ),
  t(
    "philosophy.card6.image",
    "headings",
    "Philosophie — Karte 6 Bild",
    "/images/philosophy/fleischermeister-leidenschaft.png",
  ),
  t(
    "philosophy.card6.image_alt",
    "headings",
    "Philosophie — Karte 6 Alternativtext",
    "Meisterbrief — Fleischermeister Ralf Hermanski, Handwerkskammer Düsseldorf 1994",
  ),
  t("philosophy.card6.caption", "headings", "Philosophie — Karte 6 Bildunterschrift", ""),

  t("home.latest.eyebrow", "headings", "Startseite — Neueste Kurse Eyebrow", "Frisch aus der Akademie"),
  t("home.latest.title", "headings", "Startseite — Neueste Kurse Titel", "Neueste Kurse"),
  t("home.latest.link", "buttons", "Startseite — Neueste Kurse Link", "Alle Kurse →"),
  t("home.tools.eyebrow", "headings", "Startseite — Werkstatt Eyebrow", "Werkstatt"),
  t(
    "home.tools.title",
    "headings",
    "Startseite — Werkstatt Titel",
    "Präzise Werkzeuge für dein Handwerk",
  ),
  t(
    "home.tools.description",
    "headings",
    "Startseite — Werkstatt Beschreibung",
    "Vom Salzrechner bis zur Rezeptanalyse – digitale Helfer, die im Alltag wirklich zählen.",
  ),
  t("home.membership.eyebrow", "headings", "Startseite — Mitgliedschaft Eyebrow", "Mitgliedschaft"),
  t(
    "home.membership.title",
    "headings",
    "Startseite — Mitgliedschaft Titel",
    "Wähle deinen Weg zum Handwerk",
  ),
  t(
    "home.membership.description",
    "headings",
    "Startseite — Mitgliedschaft Beschreibung",
    "Vier Stufen – vom Wurst Club bis zur Meisterklasse. Jederzeit kündbar.",
  ),
  t(
    "home.testimonials.eyebrow",
    "headings",
    "Startseite — Testimonials Eyebrow",
    "Stimmen aus der Community",
  ),
  t(
    "home.testimonials.title",
    "headings",
    "Startseite — Testimonials Titel",
    "Was unsere Mitglieder sagen",
  ),
  t(
    "home.testimonials.description",
    "headings",
    "Startseite — Testimonials Beschreibung (veraltet)",
    "Über 2.500 Wurst-Handwerker lernen und tüfteln bereits mit Alles-Wurst.",
  ),
  t(
    "homepage.reviews.eyebrow",
    "headings",
    "Startseite — Community-Bewertungen Eyebrow",
    "Stimmen aus der Community",
  ),
  t(
    "homepage.members.eyebrow",
    "headings",
    "Startseite — Community-Mitglieder Eyebrow",
    "Unsere Community",
  ),
  t(
    "homepage.members.title",
    "headings",
    "Startseite — Community-Mitglieder Titel",
    "Wurstfreunde auf Alles Wurst",
  ),
  t(
    "homepage.members.subtitle",
    "headings",
    "Startseite — Community-Mitglieder Untertitel",
    "Bereits {{memberCount}} registrierte Mitglieder sind dabei.",
  ),
  t(
    "homepage.reviews.title",
    "headings",
    "Startseite — Community-Bewertungen Titel",
    "Was unsere Mitglieder sagen",
  ),
  t(
    "homepage.reviews.subtitle",
    "headings",
    "Startseite — Community-Bewertungen Untertitel",
    "Bereits {{memberCount}} Wurstfreunde lernen und tüfteln mit Alles Wurst.",
  ),
  t(
    "homepage.reviews.empty.title",
    "headings",
    "Startseite — Community-Bewertungen Leer Titel",
    "Noch keine Bewertungen",
  ),
  t(
    "homepage.reviews.empty.description",
    "text",
    "Startseite — Community-Bewertungen Leer Text",
    "Dieser Bereich wird mit den ersten freigegebenen Bewertungen unserer Mitglieder gefüllt.",
  ),
  t(
    "homepage.reviews.source.platform",
    "text",
    "Startseite — Bewertungsquelle Plattform",
    "Plattform",
  ),
  t(
    "homepage.reviews.source.course",
    "text",
    "Startseite — Bewertungsquelle Kurs",
    "Kurs",
  ),
  t(
    "homepage.reviews.readMore",
    "buttons",
    "Startseite — Bewertung Weiterlesen",
    "Weiterlesen",
  ),
  t(
    "homepage.reviews.previous",
    "buttons",
    "Startseite — Vorherige Bewertung",
    "Vorherige Bewertung",
  ),
  t(
    "homepage.reviews.next",
    "buttons",
    "Startseite — Nächste Bewertung",
    "Nächste Bewertung",
  ),
  t("home.help.eyebrow", "headings", "Startseite — Hilfe Eyebrow", "Hilfe & Unterstützung"),
  t(
    "home.help.title",
    "headings",
    "Startseite — Hilfe Titel",
    "Hilfe, wenn du nicht weiterkommst",
  ),
  t(
    "home.help.description",
    "headings",
    "Startseite — Hilfe Beschreibung",
    "Egal ob Kursfrage, Rezeptproblem oder technische Unterstützung – wir begleiten dich auf deinem Weg zum besseren Handwerk.",
  ),
  t("home.help.cta_title", "headings", "Startseite — Hilfe CTA Titel", "Gemeinsam schneller ans Ziel."),
  t(
    "home.help.cta_description",
    "headings",
    "Startseite — Hilfe CTA Beschreibung",
    "Wissensdatenbank, Support und Community – alles an einem Ort, damit du dich auf das konzentrieren kannst, was zählt: dein Handwerk.",
  ),
  t("home.help.cta_button", "buttons", "Startseite — Hilfe CTA Button", "Hilfe entdecken"),
  t("help.title", "headings", "Hilfe — Titel", "Hilfe & Unterstützung"),
  t(
    "help.subtitle",
    "headings",
    "Hilfe — Untertitel",
    "Finde schnell Antworten, stelle Fragen oder kontaktiere den Support.",
  ),
  t("help.knowledge.title", "headings", "Hilfe — Wissensdatenbank Titel", "Wissensdatenbank"),
  t(
    "help.knowledge.description",
    "headings",
    "Hilfe — Wissensdatenbank Beschreibung",
    "Antworten auf häufige Fragen, Anleitungen und Hilfestellungen.",
  ),
  t("help.tickets.title", "headings", "Hilfe — Tickets Titel", "Support-Tickets"),
  t(
    "help.tickets.description",
    "headings",
    "Hilfe — Tickets Beschreibung",
    "Stelle deine Fragen strukturiert und verfolge den Bearbeitungsstand.",
  ),
  t("help.community.title", "headings", "Hilfe — Community Titel", "Community Forum"),
  t(
    "help.community.description",
    "headings",
    "Hilfe — Community Beschreibung",
    "Tausche Erfahrungen aus und lerne von anderen Mitgliedern.",
  ),
  t("help.master.title", "headings", "Hilfe — Meister-Support Titel", "Meister-Support"),
  t(
    "help.master.description",
    "headings",
    "Hilfe — Meister-Support Beschreibung",
    "Exklusive Unterstützung für Meisterclub-Mitglieder.",
  ),
  t("help.search.placeholder", "buttons", "Hilfe — Suchfeld Platzhalter", "Wonach suchst du?"),
  t(
    "help.noResults.title",
    "headings",
    "Hilfe — Keine Suchergebnisse Titel",
    "Keine passende Antwort gefunden?",
  ),
  t(
    "help.noResults.description",
    "headings",
    "Hilfe — Keine Suchergebnisse Beschreibung",
    "Wir helfen dir gerne persönlich weiter.",
  ),
  t("help.createTicket", "buttons", "Hilfe — Ticket erstellen", "Support-Ticket erstellen"),
  t("help.askCommunity", "buttons", "Hilfe — Zum Forum", "Zum Forum"),
  t(
    "help.masterSupportLocked",
    "headings",
    "Hilfe — Meister-Support gesperrt",
    "Der Meister-Support ist exklusiv für Mitglieder der Meisterklasse.",
  ),
  t("homepage.social.eyebrow", "headings", "Startseite — Social Eyebrow", "Community"),
  t(
    "homepage.social.title",
    "headings",
    "Startseite — Social Titel",
    "Werde Teil der Alles-Wurst Community",
  ),
  t(
    "homepage.social.subtitle",
    "headings",
    "Startseite — Social Untertitel",
    "Folge uns auf Social Media und nimm an der monatlichen Wurst-Challenge teil.",
  ),
  t("homepage.social.follow", "headings", "Startseite — Social Follower", "Abonnenten"),
  t("homepage.social.openProfile", "buttons", "Startseite — Social Profil", "Profil öffnen"),
  t("homepage.social.latestPost", "buttons", "Startseite — Neuester Beitrag", "Neuester Beitrag"),
  t(
    "homepage.social.unavailable",
    "headings",
    "Startseite — Social nicht verfügbar",
    "Social-Media-Kanäle werden in Kürze hier angezeigt.",
  ),
  t("admin.social.setup.title", "headings", "Admin — Social Einrichtung Titel", "Social-Media-Einrichtung"),
  t(
    "admin.social.setup.description",
    "headings",
    "Admin — Social Einrichtung Beschreibung",
    "Schritt für Schritt zur vollständigen Einrichtung von Social Media und Synchronisierung.",
  ),
  t("admin.social.setup.channels", "headings", "Admin — Social Kanäle", "Social-Media-Kanäle"),
  t("admin.social.setup.youtube", "headings", "Admin — YouTube", "YouTube-Schnittstelle"),
  t("admin.social.setup.manualPosts", "headings", "Admin — Manuelle Beiträge", "Manuelle Beiträge"),
  t("admin.social.setup.cron", "headings", "Admin — Cronjob", "Cronjob"),
  t("admin.social.setup.preview", "headings", "Admin — Startseiten-Vorschau", "Startseiten-Vorschau"),
  t("admin.social.setup.test", "headings", "Admin — Funktionstest", "Funktionstest"),
  t("admin.social.status.notConfigured", "headings", "Admin — Status nicht eingerichtet", "Nicht eingerichtet"),
  t("admin.social.status.partial", "headings", "Admin — Status teilweise", "Teilweise eingerichtet"),
  t("admin.social.status.ready", "headings", "Admin — Status bereit", "Eingerichtet"),
  t("admin.social.status.error", "headings", "Admin — Status Fehler", "Fehler"),
  t("admin.social.status.testPassed", "headings", "Admin — Status Test bestanden", "Test bestanden"),
  t(
    "admin.social.youtube.connectionSuccess",
    "headings",
    "Admin — YouTube Verbindung OK",
    "Die YouTube-Verbindung wurde erfolgreich getestet.",
  ),
  t(
    "admin.social.youtube.connectionFailed",
    "headings",
    "Admin — YouTube Verbindung fehlgeschlagen",
    "Die YouTube-Verbindung konnte nicht getestet werden.",
  ),
  t(
    "admin.social.youtube.apiKeyMissing",
    "headings",
    "Admin — YouTube API-Key fehlt",
    "Der YouTube-API-Schlüssel wurde noch nicht eingerichtet.",
  ),
  t(
    "admin.social.youtube.channelMissing",
    "headings",
    "Admin — YouTube Kanal-ID fehlt",
    "Die YouTube-Kanal-ID wurde noch nicht eingerichtet.",
  ),
  t(
    "admin.social.cron.secretMissing",
    "headings",
    "Admin — Cron-Secret fehlt",
    "Das Cron-Secret fehlt oder ist zu kurz.",
  ),
  t(
    "admin.social.cron.secretInvalid",
    "headings",
    "Admin — Cron-Secret ungültig",
    "Das Cron-Secret verwendet einen unsicheren Wert.",
  ),
  t("admin.social.cron.lastRun", "headings", "Admin — Letzter Cron-Lauf", "Letzter Cron-Aufruf"),
  t("admin.social.cron.testRun", "buttons", "Admin — Cron simulieren", "Cronjob lokal simulieren"),
  t("admin.challenge.testCreate", "buttons", "Admin — Test-Challenge anlegen", "Test-Challenge anlegen"),
  t("admin.challenge.testDelete", "buttons", "Admin — Testdaten löschen", "Alle Testdaten löschen"),
  t(
    "admin.challenge.testWarning",
    "headings",
    "Admin — Testdaten Warnung",
    "Nur in Entwicklung oder Staging verfügbar. Vor Produktivstart alle Testdaten entfernen.",
  ),
  t(
    "homepage.challenge.badge",
    "headings",
    "Startseite — Challenge Badge",
    "Wurst-Challenge des Monats",
  ),
  t("homepage.challenge.view", "buttons", "Startseite — Challenge ansehen", "Challenge ansehen"),
  t(
    "homepage.challenge.participate",
    "buttons",
    "Startseite — Challenge teilnehmen",
    "Jetzt teilnehmen",
  ),
  t(
    "homepage.challenge.firstSubmission",
    "headings",
    "Startseite — Erster Beitrag",
    "Sei der Erste und reiche deinen Beitrag ein.",
  ),
  t(
    "homepage.challenge.noActive",
    "headings",
    "Startseite — Keine Challenge",
    "Aktuell läuft keine Challenge.",
  ),
  t("challenge.popup.eyebrow", "headings", "Challenge-Popup Eyebrow", "Neue Challenge"),
  t("challenge.popup.view", "buttons", "Challenge-Popup ansehen", "Challenge ansehen"),
  t("challenge.popup.participate", "buttons", "Challenge-Popup teilnehmen", "Jetzt teilnehmen"),
  t("challenge.popup.remindLater", "buttons", "Challenge-Popup später", "Später erinnern"),
  t("challenge.popup.dismiss", "buttons", "Challenge-Popup ausblenden", "Nicht mehr anzeigen"),
  t("member.challenge.title", "headings", "Mein Bereich — Challenge Titel", "Aktuelle Challenge"),
  t(
    "member.challenge.daysRemaining",
    "headings",
    "Mein Bereich — Verbleibende Tage",
    "Noch {{daysRemaining}} Tage",
  ),
  t(
    "member.challenge.continueDraft",
    "buttons",
    "Mein Bereich — Entwurf fortsetzen",
    "Entwurf fortsetzen",
  ),
  t(
    "member.challenge.viewSubmission",
    "buttons",
    "Mein Bereich — Einsendung ansehen",
    "Einsendung ansehen",
  ),
  t(
    "member.challenge.viewResults",
    "buttons",
    "Mein Bereich — Ergebnisse",
    "Ergebnisse ansehen",
  ),
  t("home.blog.eyebrow", "headings", "Startseite — Magazin Eyebrow", "Magazin"),
  t("home.blog.title", "headings", "Startseite — Magazin Titel", "Neueste Beiträge"),
  t("home.blog.link", "buttons", "Startseite — Magazin Link", "Alle Beiträge →"),
  t("home.community.eyebrow", "headings", "Startseite — Community Eyebrow", "Community"),
  t(
    "home.community.title",
    "headings",
    "Startseite — Community Titel",
    "Werde Teil der Alles-Wurst Community",
  ),
  t(
    "home.community.description",
    "headings",
    "Startseite — Community Beschreibung",
    "Neue Rezepte, Tipps, Herausforderungen und Einblicke direkt aus der Praxis – hier passiert ständig etwas.",
  ),
  t("home.community_cta.title", "headings", "Startseite — Community-CTA Titel", "Werde Teil der Community"),
  t(
    "home.community_cta.description",
    "headings",
    "Startseite — Community-CTA Beschreibung",
    "Tausche dich im Forum aus, teile deine Rezepte und lerne von Meistern ihres Fachs.",
  ),
  t("home.community_cta.primary", "buttons", "Startseite — Community-CTA primär", "Community entdecken"),
  t("home.community_cta.secondary", "buttons", "Startseite — Community-CTA sekundär", "Kontakt aufnehmen"),

  // Akademie — Header
  t("akademie.header.eyebrow", "headings", "Akademie — Header Eyebrow", "Akademie"),
  t(
    "akademie.header.title",
    "headings",
    "Akademie — Header Titel",
    "Lernen mit System – von den Grundlagen bis zur Meisterschaft",
  ),
  t(
    "akademie.header.description",
    "headings",
    "Akademie — Header Beschreibung",
    "Jeder Kurs ist in Module und Lektionen gegliedert und schließt mit einem Zertifikat ab. Starte im Katalog und lerne in deinem Tempo.",
  ),
  t("akademie.header.image", "headings", "Akademie — Header Bild", "/akademie-header.png"),
  t(
    "akademie.header.image_alt",
    "headings",
    "Akademie — Header Bild Alternativtext",
    "Wurstwaren auf einem Holzbrett",
  ),

  // Werkstatt — Header
  t("werkstatt.header.eyebrow", "headings", "Werkstatt — Header Eyebrow", "Werkstatt"),
  t(
    "werkstatt.header.title",
    "headings",
    "Werkstatt — Header Titel",
    "Werkzeuge für dein Handwerk",
  ),
  t(
    "werkstatt.header.description",
    "headings",
    "Werkstatt — Header Beschreibung",
    "Präzise Rechner und Generatoren für den Alltag am Wurstkessel – plus kuratierte Ausrüstung.",
  ),
  t("werkstatt.header.image", "headings", "Werkstatt — Header Bild", ""),
  t("werkstatt.header.image_alt", "headings", "Werkstatt — Header Bild Alternativtext", ""),

  // Footer
  t("footer.tagline", "footer", "Footer — Tagline", "Die digitale Heimat für handwerkliche Wurstherstellung, Räuchern und Fleischverarbeitung."),
  t("footer.copyright", "footer", "Footer — Copyright", "© {year} Alles-Wurst. Alle Rechte vorbehalten."),
  t("footer.motto", "footer", "Footer — Motto", "The Crest of Craftsmanship"),
  t("footer.col.platform", "footer", "Footer — Spalte Plattform", "Plattform"),
  t("footer.col.account", "footer", "Footer — Spalte Konto", "Konto"),
  t("footer.col.legal", "footer", "Footer — Spalte Rechtliches", "Rechtliches"),
  t("footer.link.akademie", "footer", "Footer — Link Akademie", "Akademie"),
  t("footer.link.rezepte", "footer", "Footer — Link Rezepte", "Rezepte"),
  t("footer.link.werkstatt", "footer", "Footer — Link Werkstatt", "Werkstatt"),
  t("footer.link.community", "footer", "Footer — Link Community", "Community"),
  t("footer.link.membership", "footer", "Footer — Link Mitgliedschaft", "Mitgliedschaft"),
  t("footer.link.my_area", "footer", "Footer — Link Mein Bereich", "Mein Bereich"),
  t("footer.link.admin", "footer", "Footer — Link Admin", "Admin"),
  t("footer.link.contact", "footer", "Footer — Link Kontakt", "Kontakt"),
  t("footer.link.imprint", "footer", "Footer — Link Impressum", "Impressum"),
  t("footer.link.privacy", "footer", "Footer — Link Datenschutz", "Datenschutzerklärung"),
  t("footer.link.terms", "footer", "Footer — Link AGB", "AGB"),
  t("footer.link.withdrawal_policy", "footer", "Footer — Link Widerrufsbelehrung", "Widerrufsbelehrung"),
  t("footer.link.withdrawal_form", "footer", "Footer — Link Widerrufsformular", "Widerrufsformular"),
  t("footer.link.cookie_settings", "footer", "Footer — Link Cookie-Einstellungen", "Cookie-Einstellungen"),
  t("footer.link.legal_overview", "footer", "Footer — Link Rechtliches", "Rechtliches"),

  // Legal — öffentliche UI
  t("legal.overview.title", "legal", "Rechtliches — Überschrift", "Rechtliches"),
  t("legal.lastUpdated", "legal", "Rechtliches — Stand", "Stand"),
  t("legal.version", "legal", "Rechtliches — Version", "Version"),
  t("legal.print", "legal", "Rechtliches — Drucken", "Drucken"),
  t("withdrawal.button", "legal", "Widerruf — Button", "Vertrag widerrufen"),
  t("withdrawal.form.title", "legal", "Widerrufsformular — Titel", "Widerrufsformular"),
  t("account.orders.withdrawalButton", "account", "Bestellungen — Widerrufsbutton", "Vertrag widerrufen"),
  t("account.orders.withdrawalExisting", "account", "Bestellungen — Offener Widerruf", "Offene Widerrufsanfrage"),
  t("account.orders.withdrawalExpiredNotice", "account", "Bestellungen — Frist-Hinweis", "Die reguläre Widerrufsfrist könnte bereits abgelaufen sein. Du kannst deine Erklärung dennoch absenden. Sie wird individuell geprüft."),
  t("account.orders.legalDocumentsTitle", "account", "Bestellungen — Vertragsunterlagen Titel", "Deine Vertragsunterlagen"),
  t("account.orders.legalDocumentsDescription", "account", "Bestellungen — Vertragsunterlagen Hinweis", "Diese Unterlagen entsprechen den Fassungen, die zum Zeitpunkt deines Kaufs gültig waren."),
  t("account.orders.downloadPdf", "account", "Bestellungen — PDF Download", "PDF herunterladen"),
  t("withdrawal.confirm.title", "legal", "Widerruf — Bestätigung Titel", "Widerruf bestätigen"),
  t("withdrawal.confirm.description", "legal", "Widerruf — Bestätigung Text", "Du möchtest den folgenden Vertrag widerrufen:"),
  t("withdrawal.confirm.checkbox", "legal", "Widerruf — Bestätigung Checkbox", "Ich erkläre, dass ich den oben genannten Vertrag widerrufen möchte."),
  t("withdrawal.confirm.submit", "legal", "Widerruf — Absenden", "Widerruf verbindlich absenden"),
  t("withdrawal.received.title", "legal", "Widerruf — Eingang Titel", "Widerruf erhalten"),
  t("withdrawal.received.description", "legal", "Widerruf — Eingang Text", "Wir haben deine Widerrufserklärung erhalten. Sie wird geprüft."),
  t("privacy.center.title", "privacy", "Datenschutz — Titel", "Datenschutz"),
  t("privacy.center.description", "privacy", "Datenschutz — Beschreibung", "Dein Datenschutz-Center: Daten einsehen, exportieren und Löschanträge stellen."),
  t("privacy.center.myData", "privacy", "Datenschutz — Meine Daten", "Meine Daten"),
  t("privacy.center.export", "privacy", "Datenschutz — Export", "Datenexport"),
  t("privacy.center.consents", "privacy", "Datenschutz — Einwilligungen", "Einwilligungen"),
  t("privacy.center.requests", "privacy", "Datenschutz — Anfragen", "Datenschutzanfragen"),
  t("privacy.center.deleteAccount", "privacy", "Datenschutz — Konto löschen", "Konto und Daten löschen"),
  t("privacy.deletion.title", "privacy", "Löschung — Titel", "Konto und Daten löschen"),
  t("privacy.deletion.warning", "privacy", "Löschung — Warnung", "Rechnungen und Vertragsnachweise können gesetzlich aufbewahrt werden."),
  t("privacy.deletion.firstConfirm", "privacy", "Löschung — Erste Bestätigung", "Möchtest du die Löschung deines Kontos wirklich beantragen?"),
  t("privacy.deletion.sendEmail", "privacy", "Löschung — E-Mail senden", "Bestätigungs-E-Mail senden"),
  t("privacy.deletion.emailSent", "privacy", "Löschung — E-Mail gesendet", "Bestätigungs-E-Mail wurde gesendet."),
  t("privacy.deletion.finalTitle", "privacy", "Löschung — Finale Bestätigung", "Letzte Bestätigung"),
  t("privacy.deletion.finalConfirm", "privacy", "Löschung — Endgültig bestätigen", "Löschung endgültig bestätigen"),
  t("privacy.deletion.cancel", "privacy", "Löschung — Abbrechen", "Abbrechen"),
  t("privacy.deletion.blocked", "privacy", "Löschung — Blockiert", "Löschung derzeit blockiert"),
  t("privacy.deletion.partial", "privacy", "Löschung — Teilweise", "Löschung teilweise durchgeführt"),
  t("privacy.deletion.completed", "privacy", "Löschung — Abgeschlossen", "Kontolöschung abgeschlossen"),
  t("privacy.export.request", "privacy", "Export — Anfordern", "Meine Daten anfordern"),
  t("privacy.export.emailConfirm", "privacy", "Export — E-Mail bestätigen", "Bestätigungs-E-Mail gesendet"),
  t("privacy.export.processing", "privacy", "Export — In Arbeit", "Datenexport wird vorbereitet"),
  t("privacy.export.ready", "privacy", "Export — Bereit", "Datenexport bereit"),
  t("privacy.export.download", "privacy", "Export — Herunterladen", "ZIP herunterladen"),
  t("privacy.export.expired", "privacy", "Export — Abgelaufen", "Datenexport abgelaufen"),

  // Admin — E-Mail-Center
  t("admin.email.title", "admin", "E-Mail — Titel", "E-Mail"),
  t("admin.email.description", "admin", "E-Mail — Beschreibung", "Zentrales E-Mail-Center der Plattform"),
  t("admin.email.senders", "admin", "E-Mail — Absender", "Absenderadressen"),
  t("admin.email.providers", "admin", "E-Mail — Provider", "Provider"),
  t("admin.email.templates", "admin", "E-Mail — Vorlagen", "Vorlagen"),
  t("admin.email.queue", "admin", "E-Mail — Warteschlange", "Warteschlange"),
  t("admin.email.logs", "admin", "E-Mail — Protokoll", "Versandprotokoll"),
  t("admin.email.errors", "admin", "E-Mail — Fehler", "Zustellfehler"),
  t("admin.email.test", "admin", "E-Mail — Test", "Testversand"),
  t("admin.email.status.configured", "admin", "E-Mail — Konfiguriert", "Eingerichtet"),
  t("admin.email.status.notConfigured", "admin", "E-Mail — Nicht konfiguriert", "Nicht eingerichtet"),
  t("admin.email.status.verified", "admin", "E-Mail — Verifiziert", "Verifiziert"),
  t("admin.email.status.notVerified", "admin", "E-Mail — Nicht verifiziert", "Nicht verifiziert"),
  t("admin.email.status.error", "admin", "E-Mail — Fehlerstatus", "Fehler"),
  t("admin.email.send.title", "admin", "E-Mail — Versand", "Manueller Versand"),
  t("admin.email.send.recipient", "admin", "E-Mail — Empfänger", "Empfänger"),
  t("admin.email.send.sender", "admin", "E-Mail — Absender wählen", "Absender"),
  t("admin.email.send.template", "admin", "E-Mail — Vorlage wählen", "Vorlage"),
  t("admin.email.send.preview", "admin", "E-Mail — Vorschau", "Vorschau"),
  t("admin.email.send.test", "admin", "E-Mail — Test senden", "Test senden"),
  t("admin.email.send.confirm", "admin", "E-Mail — Bestätigen", "Versand bestätigen"),
  t("admin.email.send.success", "admin", "E-Mail — Erfolg", "Die E-Mail wurde erfolgreich versendet."),
  t("admin.email.send.failed", "admin", "E-Mail — Fehlgeschlagen", "Die E-Mail konnte nicht zugestellt werden."),
  t("account.emailPreferences.title", "account", "E-Mail-Präferenzen — Titel", "E-Mail-Benachrichtigungen"),
  t("account.emailPreferences.description", "account", "E-Mail-Präferenzen — Beschreibung", "Verwalte freiwillige E-Mail-Kategorien."),
  t("account.emailPreferences.required", "account", "E-Mail-Präferenzen — Pflicht", "Diese E-Mails sind für dein Konto erforderlich."),
  t("account.emailPreferences.optional", "account", "E-Mail-Präferenzen — Optional", "Freiwillige Benachrichtigungen"),
  t("email.footer.legal", "emails", "Footer — Rechtliches", "Rechtliche Hinweise"),
  t("email.footer.privacy", "emails", "Footer — Datenschutz", "Datenschutz"),
  t("email.footer.imprint", "emails", "Footer — Impressum", "Impressum"),
  t("email.footer.unsubscribe", "emails", "Footer — Abmelden", "Abmelden"),
  t("email.footer.automatedMessage", "emails", "Footer — Automatisch", "Diese Nachricht wurde automatisch versendet."),

  t("checkout.immediateAccess.title", "legal", "Checkout — Sofortzugang Titel", "Sofortige Bereitstellung"),
  t("checkout.delayedAccess.notice", "legal", "Checkout — Verzögerter Zugang", "Dein Kurszugang wird nach Ablauf der Widerrufsfrist freigeschaltet."),

  // Auth — Login
  t("auth.login.title", "auth", "Login — Überschrift", "Anmelden"),
  t("auth.login.subtitle", "auth", "Login — Untertitel", "Melde dich mit deiner E-Mail an. Vorhandene Rezepte aus dem Rezeptgenerator werden automatisch verknüpft."),
  t("auth.login.submit", "buttons", "Login — Button", "Anmelden"),
  t("auth.login.loading", "auth", "Login — Ladehinweis", "Formular wird geladen …"),
  t("auth.login.forgot_password", "auth", "Login — Passwort vergessen", "Passwort vergessen?"),
  t("auth.login.no_account", "auth", "Login — Kein Konto", "Noch kein Konto?"),
  t("auth.login.register_link", "auth", "Login — Registrieren-Link", "Jetzt registrieren"),

  // Auth — Register
  t("auth.register.title", "auth", "Registrierung — Überschrift", "Registrieren"),
  t("auth.register.subtitle", "auth", "Registrierung — Untertitel", "Erstelle dein kostenloses Konto für Rezepte, Werkstatt-Tools und Community."),
  t("auth.register.submit", "buttons", "Registrierung — Button", "Konto erstellen"),
  t("auth.register.has_account", "auth", "Registrierung — Bereits Konto", "Bereits registriert?"),
  t("auth.register.login_link", "auth", "Registrierung — Login-Link", "Zum Login"),

  // Auth — Password reset
  t("auth.reset.title", "auth", "Passwort-Reset — Überschrift", "Passwort zurücksetzen"),
  t("auth.reset.subtitle", "auth", "Passwort-Reset — Untertitel", "Gib deine E-Mail-Adresse ein. Wir senden dir einen Link zum Zurücksetzen."),
  t("auth.reset.submit", "buttons", "Passwort-Reset — Button", "Link senden"),
  t("auth.reset.back_login", "auth", "Passwort-Reset — Zurück", "Zurück zum Login"),

  // Dashboard / Mein Bereich
  t("dashboard.title", "dashboard", "Mein Bereich — Titel", "Mein Bereich"),
  t("dashboard.welcome", "dashboard", "Mein Bereich — Begrüßung", "Willkommen zurück bei Alles Wurst."),
  t("dashboard.empty", "dashboard", "Mein Bereich — Leer", "Hier erscheinen bald deine persönlichen Inhalte und Fortschritte."),

  // Mitgliedschaft
  t("member.title", "member", "Mitgliedschaft — Titel", "Mitgliedschaft"),
  t("member.subtitle", "member", "Mitgliedschaft — Untertitel", "Wähle die Stufe, die zu deiner Wurst-Leidenschaft passt."),
  t("member.cta.join", "buttons", "Mitgliedschaft — Beitreten", "Jetzt beitreten"),

  // Checkout
  t("checkout.title", "checkout", "Checkout — Titel", "Checkout"),
  t("checkout.subtitle", "checkout", "Checkout — Untertitel", "Schließe deine Mitgliedschaft oder Bestellung sicher ab."),
  t("checkout.pay", "buttons", "Checkout — Bezahlen", "Jetzt bezahlen"),
  t("checkout.success", "success", "Checkout — Erfolg", "Zahlung erfolgreich — vielen Dank!"),
  t("checkout.cancel", "errors", "Checkout — Abbruch", "Die Zahlung wurde abgebrochen."),

  // Forum
  t("forum.title", "forum", "Forum — Titel", "Community & Foren"),
  t("forum.empty", "forum", "Forum — Leer", "Noch keine Beiträge in diesem Forum."),
  t("forum.new_topic", "buttons", "Forum — Neues Thema", "Neues Thema"),

  // Tickets
  t("tickets.title", "tickets", "Support — Titel", "Support & Tickets"),
  t("tickets.new", "buttons", "Support — Neues Ticket", "Neues Ticket"),
  t("tickets.empty", "tickets", "Support — Leer", "Du hast noch keine Support-Tickets."),
  t("tickets.reply_placeholder", "forms", "Support — Antwort-Platzhalter", "Deine Nachricht an den Support …"),

  // Blog
  t("blog.title", "blog", "Magazin — Titel", "Magazin"),
  t("blog.subtitle", "blog", "Magazin — Untertitel", "Wissen, Rezepte und Geschichten rund um die Wurst."),
  t("blog.read_more", "buttons", "Magazin — Weiterlesen", "Weiterlesen"),

  // Kurse
  t("courses.title", "courses", "Akademie — Titel", "Akademie"),
  t("courses.subtitle", "courses", "Akademie — Untertitel", "Lerne Wurstherstellung Schritt für Schritt."),
  t("courses.enroll", "buttons", "Kurs — Einschreiben", "Kurs starten"),
  t("courses.continue", "buttons", "Kurs — Fortsetzen", "Weitermachen"),

  // Formulare (allgemein)
  t("forms.required_hint", "forms", "Formular — Pflichtfelder", "Mit * markierte Felder sind Pflichtfelder."),
  t("forms.save", "buttons", "Formular — Speichern", "Speichern"),
  t("forms.cancel", "buttons", "Formular — Abbrechen", "Abbrechen"),
  t("forms.search_placeholder", "forms", "Formular — Suche", "Suchen …"),

  // Fehler / Erfolg (allgemein)
  t("errors.generic", "errors", "Allgemein — Fehler", "Ein Fehler ist aufgetreten. Bitte versuche es später erneut."),
  t("errors.not_found", "errors", "Allgemein — Nicht gefunden", "Die angeforderte Seite wurde nicht gefunden."),
  t("errors.forbidden", "errors", "Allgemein — Verboten", "Du hast keine Berechtigung für diese Aktion."),
  t("errors.validation", "errors", "Allgemein — Validierung", "Bitte prüfe deine Eingaben."),
  t("success.saved", "success", "Allgemein — Gespeichert", "Änderungen wurden gespeichert."),
  t("success.sent", "success", "Allgemein — Gesendet", "Nachricht wurde erfolgreich gesendet."),

  // E-Mails
  t("emails.verify.subject", "emails", "E-Mail — Verifikation Betreff", "E-Mail-Adresse bestätigen — Alles Wurst"),
  t("emails.verify.intro", "emails", "E-Mail — Verifikation Einleitung", "bitte bestätige deine E-Mail-Adresse für dein Alles-Wurst-Konto:"),
  t("emails.verify.button", "emails", "E-Mail — Verifikation Button", "E-Mail bestätigen"),
  t("emails.verify.expiry", "emails", "E-Mail — Verifikation Gültigkeit", "Der Link ist 24 Stunden gültig."),
  t("emails.reset.subject", "emails", "E-Mail — Reset Betreff", "Passwort zurücksetzen — Alles Wurst"),
  t("emails.reset.intro", "emails", "E-Mail — Reset Einleitung", "du hast ein neues Passwort für dein Alles-Wurst-Konto angefordert:"),
  t("emails.reset.button", "emails", "E-Mail — Reset Button", "Passwort zurücksetzen"),
  t("emails.purchase.subject", "emails", "E-Mail — Kauf Betreff", "Willkommen im Club — Alles Wurst"),
  t("emails.purchase.intro", "emails", "E-Mail — Kauf Einleitung", "vielen Dank für deine Mitgliedschaft bei Alles Wurst!"),

  // Menü (Hauptnavigation)
  t("menu.akademie", "menu", "Menü — Akademie", "Akademie"),
  t("menu.werkstatt", "menu", "Menü — Werkstatt", "Werkstatt"),
  t("menu.magazin", "menu", "Menü — Magazin", "Magazin"),
  t("menu.community", "menu", "Menü — Community", "Community"),
  t("menu.membership", "menu", "Menü — Mitgliedschaft", "Mitgliedschaft"),
  t("menu.login", "menu", "Menü — Anmelden", "Anmelden"),
  t("menu.my_area", "menu", "Menü — Mein Bereich", "Mein Bereich"),
];

export const PLATFORM_TEXT_DEFAULT_MAP = new Map(
  PLATFORM_TEXT_DEFAULTS.map((entry) => [entry.key, entry]),
);

export function getPlatformTextDefault(key: string): PlatformTextDefault | undefined {
  return PLATFORM_TEXT_DEFAULT_MAP.get(key);
}

export function interpolatePlatformText(
  template: string,
  vars: Record<string, string | number> = {},
): string {
  let result = template;

  for (const [name, value] of Object.entries(vars)) {
    result = result.replaceAll(`{{${name}}}`, String(value));
    result = result.replaceAll(`{${name}}`, String(value));
  }

  return result;
}
